services:
  db:
    image: postgres:latest
    container_name: database-container
    ports:
      - 5775:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel
    restart: always
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  db-volume: