services:
  db:
    image: postgres:latest
    container_name: database1
    ports:
      - 5775:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel
    restart: always
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume: